name: tarteeb_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  camera: ^0.10.5+9
  path: ^1.8.3
  video_player: ^2.9.5
  just_audio: ^0.9.38
  lottie: ^3.1.0
  flutter_rating_bar: ^4.0.1
  google_fonts: ^6.1.0
  table_calendar: ^3.0.9
  file_picker: ^6.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/